[project]
name = "ai-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mtech Bilal", email = "bilal.360code@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.4",
    "uvicorn[standard]>=0.52.1",
]

[project.scripts]
ai-ml = "ai_ml:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
